{% set version = "57.1" %}
{% set version_under = version.replace(".", "_") %}

package:
  name: icu
  version: {{ version }}

source:
  fn:  icu4c-{{ version_under }}-src.tgz
  url: http://download.icu-project.org/files/icu4c/{{ version }}/icu4c-{{ version_under }}-src.tgz
  sha256: ff8c67cb65949b1e7808f2359f2b80f722697048e90e7cfc382ec1fe229e9581
  patches:
    # include an extra header when using mingw
    - icu4c-4_9_1-mingw-w64-mkdir-compatibility.patch  # [win]
    - 0001-fix-icudat.res-race-condition.patch
    # include stdint where appropriate (vs<2010) - do not depend on ICU's incomplete implementation
    # - stdint.patch                                     # [win and py<34]

build:
  number: 2
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]

requirements:
  build:
    # at present, m2-* packages require manual addition of the msys2 channel
    #    conda config --add channels http://repo.continuum.io/pkgs/msys2/
    - m2-base     # [win]
    - m2-bash     # [win]
    - m2-make     # [win]
    # at present, this one is only on conda-forge
    #    conda config --add channels conda-forge
    - msinttypes        # [win and py<34]

test:
  files:
    - gb-18030-2000.ucm  # from http://source.icu-project.org/repos/icu/data/trunk/charset/data/ucm/gb-18030-2000.ucm
    - de.txt          # from ICU's data folder
  commands:
    # Libraries
    {% set libs = [
       "libicudata",
       "libicui18n",
       "libicuio",
       "libicutest",
       "libicutu",
       "libicuuc"
     ] %}
    {% for each_lib in libs %}
    - test -f $PREFIX/lib/{{ each_lib }}.a                                                 # [unix]
    - test -f $PREFIX/lib/{{ each_lib }}.{{ version }}.dylib                               # [osx]
    - test -f $PREFIX/lib/{{ each_lib }}.so.{{ version }}                                  # [linux]
    {% endfor %}

    # CLI tests
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - icu-config --help
    - makeconv gb-18030-2000.ucm

about:
  home: http://site.icu-project.org/
  license: MIT
  summary: International Components for Unicode

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
